# Generated by Django 5.2 on 2026-03-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ano_lancamento', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='filmes/')),
            ],
        ),
    ]
